name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 via SSH
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (local copy for workflow metadata)
        uses: actions/checkout@v4

      - name: Deploy to EC2 over SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          script: |
            set -euo pipefail
            echo "Connected to $(hostname)"
            # Ensure the application directory exists
            APP_DIR="${{ secrets.EC2_APP_DIR }}"
            BRANCH="${{ github.ref_name }}"
            if [ -z "$APP_DIR" ]; then
              echo "Error: EC2_APP_DIR secret is not set."
              exit 2
            fi
            cd "$APP_DIR" || { echo "App dir $APP_DIR not found"; exit 1; }
            # Update the repo to the pushed branch
            git fetch --all
            git checkout "$BRANCH" || git checkout main
            git reset --hard "origin/$BRANCH"
            # Ensure deploy script is executable and run it
            chmod +x ./scripts/deploy_vps.sh
            ./scripts/deploy_vps.sh -d "$APP_DIR" -u "${{ secrets.EC2_USER }}" -b "$BRANCH"
