name: Deploy to EC2

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: "main"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      NODE_ENV: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Type check (CI safety)
        run: pnpm exec tsc --noEmit

      - name: Build Next (standalone)
        env:
          # add any NEXT_PUBLIC_* envs required for build-time if needed
          NODE_OPTIONS: --max-old-space-size=2048
        run: pnpm build

      - name: Create deploy bundle
        run: |
          mkdir -p deploy/.next deploy/public
          rsync -a .next/standalone/ deploy/.next/standalone/
          rsync -a .next/static/     deploy/.next/static/
          rsync -a public/           deploy/public/
          # include any runtime files needed (optional)
          # cp package.json deploy/    # only if your app expects it at runtime
          tar -C deploy -czf release.tar.gz .

      - name: Upload artifact (for traceability)
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: release.tar.gz
